### ISSUE TITLE
Trying to get THETA tokens into wallet - The deposit is confirmed but missing - Please help

### ISSUE THREAD

**Issue by DREWCOIN7** [thetatoken/theta-wallet-web#10]
Here is the backstory of my missing THETA. Please let me know how to resolve this.

1. I transferred 7,298 THETA last year from MyEtherWallet to Binance close to when THETA switched to their own main net. The coins never arrived in my Binance account but are confirmed on the blockchain. 
TX =
0xd9e3d9d7fd5db950446fa0ee65ac52abf4230717ae2264334e0db81895e2664e 

2. I contacted Binance and they said it is because the transfer was for the old ERC-20 THETA coins. 
![image](https://user-images.githubusercontent.com/39507370/97502776-36a52900-194a-11eb-93ee-e51d45e4219d.png)

3. Binance agreed to send it to my THETA wallet on THETA's website. The transaction is confirmed on the blockchain but never arrived to my wallet. What can I do to get my Tokens?
TX =
0x843aa42671d940bb09e3d3dceef8a9a5671f04779ff15d1eb4dd14cab18b4ad8

4. My THETA wallet
![image](https://user-images.githubusercontent.com/39507370/97502874-62c0aa00-194a-11eb-809e-70223f724933.png)

Please help me get the tokens to my THETA wallet. My deposit address is...
0xc89779d94AF20516020F516E5cB40B369Cf813F5

Thank you,

Andrew

**Comment by weslevitt** [comment]
Hi Andrew, 

All Theta tokens were swapped to the Theta blockchain when it launched in March 2019. Your tokens were created at the equivalent address to the one that held them on Ethereum (https://explorer.thetatoken.org/account/0x78E163258ba7D00aEf4AB5D814034eBED1b04693). To access your tokens, import that address into the Theta web wallet using the ETH address private key. This must be done on the Theta web wallet on PC, not the mobile Theta wallet. If your THETA tokens were stored on a Ledger/Trezor address, you can access your swapped mainnet tokens at the same address using your Ledger/Trezor with the Theta web wallet.

The old ERC20 tokens have no value and can be ignored. Any transactions you make with them after the March 12, 2019 swap date have not effect on Theta blockchain. So when you sent the ERC20 tokens to Binance (and back), nothing happened on Theta blockchain. Your tokens were still sitting in the above address the entire time.

**Comment by DREWCOIN7** [comment]
Wow, thank you so much. Can I send you a donation for your help?

**Comment by weslevitt** [comment]
No need, but thank you! Just keep supporting Theta Network

**Comment by DREWCOIN7** [comment]
I will. Thanks again.
