### ISSUE TITLE
Trezor Connect Warning

### ISSUE THREAD

**Issue by ericelliott** [thetatoken/theta-wallet-web#13]
![Screen Shot 2020-12-29 at 7 01 37 PM](https://user-images.githubusercontent.com/364727/103327180-62a36000-4a08-11eb-8c3f-8db849cdb917.png)

**Comment by mark-stopka** [comment]
I have the same issue with newer firmware 2.3.5...

![image](https://user-images.githubusercontent.com/18139116/108608222-e30d8e00-73c5-11eb-914d-e13e5528753d.png)

**Comment by mark-stopka** [comment]
Same issue with Trezor firmware `2.3.6`.

**Comment by mark-stopka** [comment]
@averytt are you guys going to look into this?

**Comment by nnmfnwl7** [comment]
By below mentioned reddit post, this issue 13 is not only warning but actually serious problem. It seems that developers do not understand this issue is serious problem and should be fixed asap. Thank you.
https://www.reddit.com/r/theta_network/comments/mgd8wi/walletthetatokenorg_is_using/

**Comment by averytt** [comment]
We have updated to TrezorConnect v8. Please let us know if you see any further issues on Trezor.
