### ISSUE TITLE
Not recieving Edge Node payouts to my Theta wallet.

### ISSUE THREAD

**Issue by juliancedrone** [thetatoken/theta-wallet-web#14]
Hello, I have been running the Theta Edge node for several weeks now and it clearly states that payouts of TFUEL are at the beginning of each month. It's over a week into 2021 and I have still not recieved a single TFUEl to my wallet. Can someone please help me figure out why I'm not getting the TFUEL the node clearly says I should have recieved a week ago?

**Comment by averytt** [comment]
@juliancedrone the Edge Node payments were sent yesterday.

**Comment by abulfouz** [comment]
same is with me not paid out

**Comment by Adam-Jack12** [comment]
@abulfouz Has your issue been resolved ?

**Comment by abulfouz** [comment]
no it is same

**Comment by Adam-Jack12** [comment]
@abulfouz Sorry to hear about your issue, you can contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking

 They'll be happy to resolve your issue. Cheers.

**Comment by Adam-Jack12** [comment]
@abulfouz Sorry to hear about your issue, you can contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking

They'll be happy to resolve your issue. Cheers.

**Comment by Adam-Jack12** [comment]
@abulfouz Sorry to hear about your issue, you can contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking

They'll be happy to resolve your issue. Cheers.
