### ISSUE TITLE
Error unstaking from guardian node after delegating to it (gpool)

### ISSUE THREAD

**Issue by korcomm** [thetatoken/theta-wallet-web#39]
Getting:
Failed to withdraw stake, err: No matched stake holder address found: 0x88884a84D980bbfB7588888126fb903486Bb8888
when trying to unstake from gpool.

This happens when clicking on the Confirm & Withdraw Stake button.  The Theta tokens were delegated to Delegated Guardian Node (gpool) just few hours ago.

**Comment by Adam-Jack12** [comment]
Hello Mate, Sorry to hear about your issue, you can contact the Theta Network Support on Telegram via the weblink www.t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by korcomm** [comment]
Ah sorry, I was selecting Validator Node instead of Guardian Node when unstaking.  It goes through now, after selecting Guardian Node.
