### ISSUE TITLE
Theta Tokens sent directly to Guardian Node

### ISSUE THREAD

**Issue by Adam-Jack12** [thetatoken/theta-wallet-web#40]
@matthewthurn. Hello mate, have you resolved your issue ?

**Comment by matthewthurn** [comment]
Still can’t get the 511 out of the contract treated as a token I’d. So
weird any ideas?

**Comment by Adam-Jack12** [comment]
Okay. Sorry to hear about your issue. You can contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking They'll be happy to resolve your issue. Cheers.

**Comment by matthewthurn** [comment]
Champion!

**Comment by Adam-Jack12** [comment]
Let me know when you have your issue resolved

cheers

**Comment by matthewthurn** [comment]
Will do, thanks!

**Comment by alekseybochkov** [comment]
The scammer is now opening their own issues. Awesome
