### ISSUE TITLE
Insufficient gas. You need at least 0.000001 TFUEL to send this transaction.

### ISSUE THREAD

**Issue by mzarsaw** [thetatoken/theta-wallet-web#43]
hi i want to send my theta coins to binance and sell it but this error accoured
Insufficient gas. You need at least 0.000001 TFUEL to send this transaction.
what's the matter?

**Comment by MattheTessitore** [comment]
Are you still able to solve the issues yet?

**Comment by mzarsaw** [comment]
thanks it's solved
