### ISSUE TITLE
How can transfer out ERC20 theta

### ISSUE THREAD

**Issue by beyondsoft978** [thetatoken/theta-wallet-web#50]
I use ledger wallet + theta web wallet
The online wallet shows the balance based on ETH and the transfer page prompts not to transfer theta to the ERC20 address
https://docs.thetatoken.org/docs/preventing-lost-eth-erc20-tokens
How can I transfer out? Currently, all exchanges are ERC20 theta addresses.

**Comment by AdamssSmith** [comment]
Hello Mate, Sorry to hear about your issue, you can join the telegram group and contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking
They'll be happy to resolve your issue. Cheers.

**Comment by AdamssSmith** [comment]
Hello Mate, Sorry to hear about your issue, you can join the telegram group and contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking
They'll be happy to resolve your issue. Cheers.

**Comment by AdamssSmith** [comment]
Hello Mate, Sorry to hear about your issue, you can join the telegram group and contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking
They'll be happy to resolve your issue. Cheers.

**Comment by beyondsoft978** [comment]
Sorry  I am in china    don’t  use telegram

发件人: Adams Shaun Smith
发送时间: 2021年7月20日 12:20
收件人: thetatoken/theta-wallet-web
抄送: beyondsoft978; Author
主题: Re: [thetatoken/theta-wallet-web] How can transfer out ERC20 theta(#50)

Hello Mate, Sorry to hear about your issue, you can join the telegram group and contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking
They'll be happy to resolve your issue. Cheers.

**Comment by AdamssSmith** [comment]
What’s your email address ??

reply with your email address in the format:   xxxxxxxx-gmail/yahoo.com

**Comment by AdamssSmith** [comment]
What’s your email address ??

Reply with your email address in the format: xxxxxxxx - yyyy .com

**Comment by beyondsoft978** [comment]
beyondsoft978@sina.com

**Comment by AdamssSmith** [comment]
@sina.com or @gmail.com ?

**Comment by AdamssSmith** [comment]
@sina.com or @gmail.com ?

**Comment by beyondsoft978** [comment]
> @sina.com or @gmail.com ?

@sina.com

**Comment by beyondsoft978** [comment]
> Have you been able to resolve your issue ?

I need help some guidance I will follow the guidance

**Comment by AdamssSmith** [comment]
Check your email address

**Comment by beyondsoft978** [comment]
Re: [thetatoken/theta-wallet-web] How can transfer out ERC20 theta(#50)

Check your email address
—
my email  is   beyondsoft978-sina.com   -is@

**Comment by AdamssSmith** [comment]
Okay. Check your spam email. You should have an email already

**Comment by beyondsoft978** [comment]
Thank you very much, the email has been received

**Comment by AdamssSmith** [comment]
Okay. Keep refreshing your spam mail every minute for quicker response
