### ISSUE TITLE
"Unexpected token < in JSON at position 1" when I try to unstake TDROP tokens partially.

### ISSUE THREAD

**Issue by kuoyaoming93** [thetatoken/theta-wallet-web#67]
Hi @jieyilong,

I noticed an issue in the web wallet when I try to unstake **partially** TDROP tokens signing with Trezor,  an unexpected error has ocurred:

![Captura de pantalla de 2022-03-01 17-39-01](https://user-images.githubusercontent.com/18518739/156211210-cb3449c7-ef8f-4461-a394-ac3ea20dc539.png)

Thank you in advance.

**Comment by jieyilong** [comment]
Thanks for reporting the issue. There was a system hiccup last night. Could you please try again to see if there are still errors?

**Comment by sureshbh11** [comment]
Hi @jieyilong:
I am getting the following error when trying to send theta (amt: 100 with 0.3 TFUEL)
from my Trezor hardware wallet (with latest firmware - the same error happened even before upgrade)
Unexpected token '<', " <html><hea"... is not valid JSON
