### ISSUE TITLE
Edge node stuck on "Fetching wallet ..." 

### ISSUE THREAD

**Issue by zdrawku** [thetatoken/theta-wallet-web#98]
Version 4.3.6 on Windows 11 Enterprise Insider Preview is not fetching the wallet.

Probably that's not the right place to ask, so feel free to direct it elsewhere.
![image](https://github.com/thetatoken/theta-wallet-web/assets/11193764/2096f48b-6dd1-41da-8c4f-3ad4bacf30b9)

**Comment by causalityloop** [comment]
You can get help in the Theta discord channel. If you go to the thetatoken website, on the top right of the page is the discord link. Good luck

**Comment by zdrawku** [comment]
I see only the Rules channel in their Discord, without the ability to write/ask a question. The other channels will probably be shown upon validating that I am not a bot or something, will wait and see.

**Comment by zdrawku** [comment]
I have upgraded to the latest desktop version today (4.3.10), but the issue remains

**Comment by zdrawku** [comment]
I believe the problem was related to the Windows 11 Insider Preview, now with Windows 11 Pro everything works fine.
